name: Astro Type Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  astro-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Astro type check
        run: bun check
